name: Provision Taarafo Core
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: windows-latest
    env:
      AzureClientId: ${{ secrets.AZURECLIENTID }}
      AzureTenantId: ${{ secrets.AZURETENANTID }}
      AzureClientSecret: ${{ secrets.AZURECLIENTSECRET }}
      AzureAdminName: ${{ secrets.AZUREADMINNAME }}
      AzureAdminAccess: ${{ secrets.AZUREADMINACCESS }}
    steps:
    - name: Check Out
      uses: actions/checkout@v2
    - name: Setup Dot Net Version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100
        include-prerelease: false
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Provision
      run: dotnet run --project .\Taarafo.Core.Infrastructure.Provision\Taarafo.Core.Infrastructure.Provision.csproj
